version: '3.8'

services:
  weather-postgres:
    image: debezium/postgres:16-alpine
    environment:
      POSTGRES_DB: weather_dev
      POSTGRES_USER: weather_dev
      POSTGRES_PASSWORD: weather_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/db

volumes:
  postgres-data:
